"""Crop real icon templates from a live Home screenshot for the CV fast-path.

The manual's placeholder icons (generated by generate_benz_manual_images.py) do
NOT match the on-screen icons, so the OpenCV fast-path never fires. This crops
the actual icon boxes from a captured Home screenshot and writes them over the
placeholders, so a re-indexed profile lets the fast-path template-match them.

Usage:
    python scripts/crop_icons_from_screenshot.py runs/<timestamp>/step-01.png

The icon centers below come from the sample IVI mock's CSS layout (three tiles;
each 74px icon sits at the tile's upper-left). Adjust ICONS for a different HMI.
Then rebuild + re-index (do NOT re-run generate_benz_manual_images.py, which
would overwrite these crops):
    ivi-agent manual build --source examples/benz-mbux-manual --output output/pdf/benz.pdf
    rm -rf knowledge/benz
    ivi-agent --config config.json knowledge index output/pdf/benz.pdf --profile benz
    ivi-agent graph build --profile benz
"""

from __future__ import annotations

import sys
from pathlib import Path

# name -> (center_x, center_y) as fractions of the screenshot, for the Home icons.
ICONS = {
    "icon-climate.png": (0.082, 0.342),
    "icon-seat-massage.png": (0.406, 0.342),
    "icon-vehicle-settings.png": (0.731, 0.342),
}
# Half box size as a fraction of width/height (a little generous around ~74px).
HALF_W = 0.045
HALF_H = 0.075
OUT_DIR = Path("examples/benz-mbux-manual/images")


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    import cv2  # local import so the repo doesn't hard-depend on opencv

    shot_path = Path(sys.argv[1])
    image = cv2.imread(str(shot_path))
    if image is None:
        print(f"could not read screenshot: {shot_path}", file=sys.stderr)
        return 1
    height, width = image.shape[:2]
    hw, hh = int(HALF_W * width), int(HALF_H * height)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, (cx, cy) in ICONS.items():
        x, y = int(cx * width), int(cy * height)
        crop = image[max(0, y - hh) : y + hh, max(0, x - hw) : x + hw]
        dest = OUT_DIR / name
        cv2.imwrite(str(dest), crop)
        print(f"wrote {dest}  {crop.shape[1]}x{crop.shape[0]}")
    print("\nOpen the crops to confirm each shows just the icon, then rebuild + re-index.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
